webtalk_init -webtalk_dir D:/carlo/git/CoE113/mp01_project_files/mp01_project_files.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 14 00:10:09 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212031164_0_0_721" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0b62ff4d-6dda-4443-b7bf-bf0355bf6ebe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "559a16d030364720bdbb15a73f612d07" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3400G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7248_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3230729087 -regid "212031164_0_0_721" -xml D:/carlo/git/CoE113/mp01_project_files/mp01_project_files.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/carlo/git/CoE113/mp01_project_files/mp01_project_files.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/carlo/git/CoE113/mp01_project_files/mp01_project_files.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
